include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Build
    - "build/**"
    # Tests
    - "test/**.mocks.dart"
    - ".test_coverage.dart"
    - "coverage/**"
    # Assets
    - "assets/**"
    # Generated
    - "**.g.dart"
    - "**.gql.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.mocks.dart"
    - "**.gen.dart"
    - "**.pb.dart"
    - "**.pbenum.dart"
    - "**.pbjson.dart"
    # Flutter Version Manager
    - ".fvm/**"
    # Tools
    - "tool/**"
    - "scripts/**"
    - ".dart_tool/**"
    # Platform
    - "ios/**"
    - "android/**"
    - "web/**"
    - "macos/**"
    - "windows/**"
    - "linux/**"
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    # Enabled
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_const_constructors: true
    cancel_subscriptions: true
    # Disabled
    sort_pub_dependencies: false
