name: initialization
description: "An initialization package"
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
