name: starty
description: "Starty"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # dart
  async: ^2.12.0
  collection: ^1.19.1
  intl: ^0.20.2
  meta: ^1.16.0
  # Monorepository shared packages
  app_utils:
    path: ../../packages/app_utils
  initialization:
    path: ../../packages/initialization
  # Internal
  l: ^5.0.0
  # Persistent and data

  # Plugins and native

  # Presentation and ui

  # Services integration

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_intl:
  enabled: true
  use_deferred_loading: false
  class_name: StartyL10n
  main_locale: en
  arb_dir: lib/src/_internal/localization/l10n
  output_dir: lib/src/_internal/localization/generated
